### ISSUE TITLE
Cursor jumps to the end of the div

### ISSUE THREAD

**Issue by endreujhelyi** [lovasoa/react-contenteditable#160]
Anywhere do I click into the component, the cursor always jumps to the end of the line.

![contenteditable](https://user-images.githubusercontent.com/18709268/56220883-80306a80-6069-11e9-837e-2ab55f4ef55b.gif)

**Comment by lovasoa** [comment]
Do you change the HTML on focus ? Because updating the html makes the cursor jump (independently of this library).

**Comment by endreujhelyi** [comment]
@lovasoa yup, I set the state what triggers the render method so the component will be re-rendered

**Comment by bayerlse** [comment]
Is there a simple workaround for this issue?

**Comment by dizsmek** [comment]
@bayerlse If you use the CSS `:focus` pseudo selector for changing the style when editing the contenteditable component, it won't re-render and that should solve the cursor positioning.

**Comment by sahibjotsaggu** [comment]
I'm having this problem too but I've verified that I'm not focusing on the ContentEditable element.

Here is a small example I've made that uses the `innerRef` prop on `ContentEditable`: https://codesandbox.io/s/youthful-feynman-fttms7?file=/src/App.js

If you type something into the ContentEditable field, and then try to type something in the middle or the beginning, the cursor gets set to the end of the content. But if you comment out the `innerRef` prop, it works fine. I'm sure this is not a bug in this package but react is working as intended.. just not sure how to get around this.

Is there a workaround for this?

**Comment by lovasoa** [comment]
@sahibjotsaggu : Looks like you are using `useState`, which triggers a rerender of the component. 

See : https://github.com/lovasoa/react-contenteditable#known-issues

**Comment by lovasoa** [comment]
Here is what I think you wanted to do: https://codesandbox.io/s/zealous-resonance-5kxwxj?file=/src/App.js

**Comment by sahibjotsaggu** [comment]
@lovasoa Thanks for the reply. The example I gave was simple where I removed the focusing logic. If we take your example and add focusing logic so that when you add a new entry, it will focus on that entry, the issue I described still exists: https://codesandbox.io/s/fervent-currying-23249x?file=/src/App.js

**Comment by lovasoa** [comment]
Your component is re-rendering every time because the value passed to innerRef is a new, different, arrow function every time

**Comment by sahibjotsaggu** [comment]
Right, do you have any insight into how can I stop the re-rendering while maintaining the focus functionality?

**Comment by lovasoa** [comment]
You could just use the object variant of innerRef instead of passing a function

**Comment by sahibjotsaggu** [comment]
But that doesn't allow me to find the `id` of the Entry that I need to focus on. The `entryRefs` is an object mapping entry ref IDs to the DOM node.

**Comment by lovasoa** [comment]
You need to call useRef in the parent component of ContentEditable, and pass the result to the innerRef property.
Once you've called useRef, you are free to pass around and store the ref element anywhere you want.

```jsx
import { useState, useRef, useEffect } from "react";
import ContentEditable from "react-contenteditable";
import { v4 as uuid } from "uuid";
import _ from "lodash";
import "./styles.css";

const Entry = ({ entry, setRef, update }) => {
  const ref = useRef();
  setRef(ref);
  return (
    <ContentEditable
      innerRef={ref}
      style={{ border: "1px solid black", marginTop: 20 }}
      html={entry.text}
      onChange={(e) => {
        update(e.target.value);
        console.log(e.target);
      }}
    />
  );
};

export default function App() {
  const [entries, setEntries] = useState([
    { id: "1", text: "", ref: null },
    { id: "2", text: "", ref: null }
  ]);
  const previousEntries = useRef([]);

  useEffect(() => {
    const addedDiff = _.differenceBy(entries, previousEntries.current, "id");

    if (addedDiff.length) {
      const [{ id }] = addedDiff;
      console.log(`focusing on entry with id: ${id}`);
      entries.find((e) => e.id === id)?.ref.current?.focus();
    }

    previousEntries.current = entries;
  }, [entries]);

  const addEntry = () => {
    setEntries([...entries, { id: uuid(), text: "", ref: null }]);
  };

  return (
    <div className="App">
      <button onClick={addEntry}>Add Entry</button>
      {entries.map((entry) => (
        <Entry
          key={entry.id}
          setRef={(ref) => (entry.ref = ref)}
          entry={entry}
          update={(text) =>
            setEntries(
              entries.map((e) => (e.id === entry.id ? { ...e, text } : e))
            )
          }
        />
      ))}

      <pre>{JSON.stringify(entries, ["id", "text"], 2)}</pre>
    </div>
  );
}
```

https://codesandbox.io/s/tender-mcnulty-m3sq2n?file=/src/App.js
