### ISSUE TITLE
How to detect keys ?

### ISSUE THREAD

**Issue by EduardJS** [lovasoa/react-contenteditable#51]
Hei!

I'm trying to figure out how to detect the enter key...
Even tried replacing ` evt.target.value = html` instead `evt.target = { value: html }`

Though I'm yet to get any results... just a bunch of undefineds.

Thanks for baring with me

**Comment by EduardJS** [comment]
Fixed by passing the full event rather than replacing it with `{ value: html }`.

**Comment by 0xc00010ff** [comment]
Can someone elaborate on how this works?
I'm trying to detect the key in my `onChange` handler, but it there are no related properties anywhere on the `event` object

```
function textInputChanged(event) {
    console.log(event)
    // {
    //   target: ...
    //   handler: ...
    // }
}

<ContentEditable className="NewTagInput" html="#" onChange={this.textInputChanged} />
```

**Comment by justinmc** [comment]
I also couldn't figure this out, and I think it's going to prevent me from using this project.  I think @EduardJS is talking about modifying the source code in his posts, which I don't want to do.

Notice that you can get access to the native event with `event.nativeEvent`, but I still don't see `keyCode` or anything that could be used to detect an enter.

**Comment by EduardJS** [comment]
The problem with not being able to listen to events is because this repo obfuscates the actual event, and uses only it's value instead. 

@justinmc After half a year of ReactJS and Native, I quickly ended up realising it is actually better to code your own stuff, or, just take code from repos like this, and change it to your own needs.

You wont be able to finish a medium sized app, with code solely taken from repos, and just link them together.

It is easier, better and more importantly `faster`, to maintain your own code. Keep in mind that having code from repos, may imply breaking changes when they update, or even unwanted bugs.

Have a great one!
